export const FIRST_ACTION = 'main/FIRST_ACTION';

export const FETCHING_USER_DATA = "FETCHING_USER_DATA";
export const FETCHING_USER_DATA_SUCCESS = "FETCHING_USER_DATA_SUCCESS";
export const FETCHING_USER_DATA_FAIL = "FETCHING_USER_DATA_FAIL";

export const FETCHING_EVENT_DATA = "FETCHING_EVENT_DATA";
export const FETCHING_EVENT_DATA_SUCCESS = "FETCHING_EVENT_DATA_SUCCESS";
export const FETCHING_EVENT_DATA_FAIL = "FETCHING_EVENT_DATA_FAIL";

export const FETCHING_GROUP_DATA = "FETCHING_GROUP_DATA";
export const FETCHING_GROUP_DATA_SUCCESS = "FETCHING_GROUP_DATA_SUCCESS";
export const FETCHING_GROUP_DATA_FAIL = "FETCHING_GROUP_DATA_FAIL";